import React from 'react';
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import TopNavar from '../TopNavbar/TopNavbar';
import ItemDesc from '../ItemDescription/ItemDesc'
import './item.css'
const Item = (props) => {
  
  const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 5
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 3
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 3
    }
  };


  return (
    <React.Fragment>
      <TopNavar/>

      <Carousel responsive={responsive} style={{marginTop:'15em'}}>
        <div>
          <img className="img" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8SDw8SDw8PFRUVDw0NFRUPDQ8NFRUVFRUWFhUVFRUYHSggGBolHRUVITEhJSktLi4uFx8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAWEAEBAQAAAAAAAAAAAAAAAAAAARH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A18EAAAAAVFAQAAAAAUEAAACgAKAgYABQRQARQBRAAAAAAUBAAAAAAUQARQAAAUBBAUAAAAACgAAAAAAAAAAAAAUAAAAAAAAAAAAAFEAFAEAAVAAFBAAAAVAAFAQABUAAAVFQAAFQAA0BUFBAAAAFQAFQAAAAFQUEAAAAVAAVAC0AAAAAVAAAAAAVAAAAAAAFQARQAAAVAAAAAAAAXAEFQAACgoIAAqABQAFQAAAACgoCAAAAAAogAAKCABgAFAAUEAwACgAAoIAAABAAUBAAAoAQAAAUQARQAAAUBAAAAAAUQAAAAAFAQAAAAAAAKAAAAAAAACggAAAAAAAAAAAAAAAAALiAAKAgACoAAoIKgAAKgAKiggACoAAoIKgAAKgABoCoKCAAUABUABUAAAABUFBAALSAAqAAqAFACAAAAqCAoAAACoAAAAAAAqAAAAAAqAAAAAAAAuIAACoAAKAgAKgAUAFEAAAAABQEAAAAAAVAAAVABUoAogAAAABQAVABagAqUAAAFQAUASgAqAAAD//Z" alt=""/>
          <div className="item_desc">Green Tea</div>
        </div>
        <div>
          <img className="img" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8SDw8SDw8PFRUVDw0NFRUPDQ8NFRUVFRUWFhUVFRUYHSggGBolHRUVITEhJSktLi4uFx8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAWEAEBAQAAAAAAAAAAAAAAAAAAARH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A18EAAAAAVFAQAAAAAUEAAACgAKAgYABQRQARQBRAAAAAAUBAAAAAAUQARQAAAUBBAUAAAAACgAAAAAAAAAAAAAUAAAAAAAAAAAAAFEAFAEAAVAAFBAAAAVAAFAQABUAAAVFQAAFQAA0BUFBAAAAFQAFQAAAAFQUEAAAAVAAVAC0AAAAAVAAAAAAVAAAAAAAFQARQAAAVAAAAAAAAXAEFQAACgoIAAqABQAFQAAAACgoCAAAAAAogAAKCABgAFAAUEAwACgAAoIAAABAAUBAAAoAQAAAUQARQAAAUBAAAAAAUQAAAAAFAQAAAAAAAKAAAAAAAACggAAAAAAAAAAAAAAAAALiAAKAgACoAAoIKgAAKgAKiggACoAAoIKgAAKgABoCoKCAAUABUABUAAAABUFBAALSAAqAAqAFACAAAAqCAoAAACoAAAAAAAqAAAAAAqAAAAAAAAuIAACoAAKAgAKgAUAFEAAAAABQEAAAAAAVAAAVABUoAogAAAABQAVABagAqUAAAFQAUASgAqAAAD//Z" alt="" />
          <div className="item_desc">White Tea</div>
        </div>
        <div>
          <img className="img" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8SDw8SDw8PFRUVDw0NFRUPDQ8NFRUVFRUWFhUVFRUYHSggGBolHRUVITEhJSktLi4uFx8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAWEAEBAQAAAAAAAAAAAAAAAAAAARH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A18EAAAAAVFAQAAAAAUEAAACgAKAgYABQRQARQBRAAAAAAUBAAAAAAUQARQAAAUBBAUAAAAACgAAAAAAAAAAAAAUAAAAAAAAAAAAAFEAFAEAAVAAFBAAAAVAAFAQABUAAAVFQAAFQAA0BUFBAAAAFQAFQAAAAFQUEAAAAVAAVAC0AAAAAVAAAAAAVAAAAAAAFQARQAAAVAAAAAAAAXAEFQAACgoIAAqABQAFQAAAACgoCAAAAAAogAAKCABgAFAAUEAwACgAAoIAAABAAUBAAAoAQAAAUQARQAAAUBAAAAAAUQAAAAAFAQAAAAAAAKAAAAAAAACggAAAAAAAAAAAAAAAAALiAAKAgACoAAoIKgAAKgAKiggACoAAoIKgAAKgABoCoKCAAUABUABUAAAABUFBAALSAAqAAqAFACAAAAqCAoAAACoAAAAAAAqAAAAAAqAAAAAAAAuIAACoAAKAgAKgAUAFEAAAAABQEAAAAAAVAAAVABUoAogAAAABQAVABagAqUAAAFQAUASgAqAAAD//Z" alt="" />
          <div className="item_desc">Hot drinks</div>
        </div>
        <div>
          <img className="img" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8SDw8SDw8PFRUVDw0NFRUPDQ8NFRUVFRUWFhUVFRUYHSggGBolHRUVITEhJSktLi4uFx8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAWEAEBAQAAAAAAAAAAAAAAAAAAARH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A18EAAAAAVFAQAAAAAUEAAACgAKAgYABQRQARQBRAAAAAAUBAAAAAAUQARQAAAUBBAUAAAAACgAAAAAAAAAAAAAUAAAAAAAAAAAAAFEAFAEAAVAAFBAAAAVAAFAQABUAAAVFQAAFQAA0BUFBAAAAFQAFQAAAAFQUEAAAAVAAVAC0AAAAAVAAAAAAVAAAAAAAFQARQAAAVAAAAAAAAXAEFQAACgoIAAqABQAFQAAAACgoCAAAAAAogAAKCABgAFAAUEAwACgAAoIAAABAAUBAAAoAQAAAUQARQAAAUBAAAAAAUQAAAAAFAQAAAAAAAKAAAAAAAACggAAAAAAAAAAAAAAAAALiAAKAgACoAAoIKgAAKgAKiggACoAAoIKgAAKgABoCoKCAAUABUABUAAAABUFBAALSAAqAAqAFACAAAAqCAoAAACoAAAAAAAqAAAAAAqAAAAAAAAuIAACoAAKAgAKgAUAFEAAAAABQEAAAAAAVAAAVABUoAogAAAABQAVABagAqUAAAFQAUASgAqAAAD//Z" alt="" />
          <div className="item_desc">Coffee</div>

        </div>
      </Carousel>

      {/* item desc */}

      <ItemDesc/>

    </React.Fragment>
  );
}

export default Item;